### ISSUE TITLE
Can't record audio on flatpak version

### ISSUE THREAD

**Issue by sgarbus** [flathub/net.ankiweb.Anki#112]
Running Pop OS. Audio works normally for other apps on the computer, however, I am unable to record audio on my new cards in Anki. In the past, I was able to use flatseal to enable access to all devices. This no longer solves the problem.

**Comment by iamdennshi** [comment]
You can revert to version `2.1.53` to resolve the voice recording issue.

```
sudo flatpak update --commit=87057906046964be6c40f3b82af9e8c3379ce6f0f97d9e956ca42a68a4051380 net.ankiweb.Anki
```

**Comment by sgarbus** [comment]
Thanks for the suggestion, but when I input the above command the response that I get is :
Looking for updates…
error: net.ankiweb.Anki not installed
I can confirm that I have Anki 2.1.66 installed.  Any suggestions?

**Comment by rayes0** [comment]
Sorry for the late response, I have not had to chance to look at issues for this package lately. Are there any errors in the console when you try to record?

**Comment by rayes0** [comment]
Closing for now as this is an old issue, please try with the latest version and re-open if you are still having problems.
