### ISSUE TITLE
Update the flatpak to 23.12.1

### ISSUE THREAD

**Issue by stflavian** [flathub/net.ankiweb.Anki#130]
Currently, when opening the flatpak version of Anki a pop-up opens saying that an update is available (to version 23.12.1). From the releases page of Anki's github repository (https://github.com/ankitects/anki/releases) I can see that a number of changes were made from 23.10.1 to 23.12.1. Are there any plans to update the current version of Anki used in the flatpak to the most current one?

**Comment by rayes0** [comment]
Latest version should be on Flathub in a few minutes!
