### ISSUE TITLE
Installation crashing in x86_64 for Chromebooks

### ISSUE THREAD

**Issue by NameLessGO** [flathub/net.ankiweb.Anki#135]
> when I open the Anki application I am prompted to select a language, after selecting English (US) the Anki application simply shuts down

Reported on:
- https://forums.ankiweb.net/t/anki-wont-open-properly-after-flatpak-install/41640
- https://forums.ankiweb.net/t/cant-download-anki-on-terminal-linux/41563/18

![image](https://github.com/flathub/net.ankiweb.Anki/assets/66227691/0159cec9-b4ea-4e60-8bb0-fdce44f73abe)

**Comment by liimma1** [comment]
It's happening to me!

**Comment by rayes0** [comment]
I doubt this is an issue with the flatpak specifically. Please try again with the latest version, and let me know if it is still an issue.

**Comment by NameLessGO** [comment]
This discussion has a few ideas to what could have caused this issue https://github.com/DavidoTek/ProtonUp-Qt/issues/312

Strangely enough, X11-override socket should have run, but it wasn't

For now, any Chromebook with this issue should try using AnkiDroid
https://play.google.com/store/apps/details?id=com.ichi2.anki&pli=1

**Comment by rayes0** [comment]
The x11 socket should only be available if there is no wayland socket. However, disabling the wayland socket manually should cause anki to run through x11: `flatpak run --nosocket=wayland net.ankiweb.Anki`

I unfortunately do not own a chromebook for troubleshooting. Can anybody with a chromebook try this?

**Comment by mzeeshi** [comment]
> The x11 socket not running is expected, because it should only be available if there is no wayland socket. Disabling the wayland socket manually should force anki to run through x11 (xwayland on chromebooks?): `flatpak run --nosocket=wayland net.ankiweb.Anki`
> 
> I unfortunately do not own a chromebook for troubleshooting. Can anybody with a chromebook try this?

luv u bro it worked and thanks a lot It was a lot of hassle to find right thing but now it worked

**Comment by pennies** [comment]
> The x11 socket not running is expected, because it should only be available if there is no wayland socket. Disabling the wayland socket manually should force anki to run through x11 (xwayland on chromebooks?): `flatpak run --nosocket=wayland net.ankiweb.Anki`
> 
> I unfortunately do not own a chromebook for troubleshooting. Can anybody with a chromebook try this?

this worked for me thank you 👍

**Comment by gregorylearns** [comment]
`flatpak run --nosocket=wayland net.ankiweb.Anki`

Also worked for me.

I ran the command below to make it somewhat permanent and not run it from the terminal every time. 

`flatpak override --user --nosocket=wayland net.ankiweb.Anki`
