### ISSUE TITLE
Missing icon on Wayland

### ISSUE THREAD

**Issue by SamuXzX** [flathub/net.ankiweb.Anki#154]
[I wrote on Anki's forum](https://forums.ankiweb.net/t/missing-icon-on-wayland-for-flatpak/46243) to ask about this, and they told me to ask the Flatpak author. I suppose here is the right spot.
I intalled Anki on Fedora 40 with Plasma 6.0.
The default protocol is Wayland and I only see the default Wayland icon:
![immagine](https://github.com/flathub/net.ankiweb.Anki/assets/30182251/1d9d7ba8-b0b5-44e8-9325-25d82a730a5d)

Anki’s Flatpak version is 24.06.2
Plasma’s version is 6.0.5
Qt is 6.7.1

**Comment by rayes0** [comment]
I cannot reproduce this. Does this only occur with the Anki flatpak, or every other flatpak as well?

Please check the contents of `$XDG_DATA_DIRS`, and ensure that it contains the flatpak icon export path. For what is supposed to happen with icons in flatpak, read here: https://docs.flatpak.org/en/latest/conventions.html#application-icons

**Comment by FrankAlbella** [comment]
I am also able to reproduce on Plasma 6.1.2, Qt 6.7.2. The icon shows up normally in the application launcher, but not in the taskbar or the Anki's titlebar. Other flatpak apps are not missing their icons. The contents of my `$XDG_DATA_DIRS` looks like this: 
```
$ echo $XDG_DATA_DIRS
/home/frank/.local/share/flatpak/exports/share /var/lib/flatpak/exports/share /usr/local/share /usr/share
```

**Comment by FrankAlbella** [comment]
It might be because the resource name (WM class) isn't set, so it can't match the icon to the .desktop file?
![image](https://github.com/user-attachments/assets/2f4cdd4c-6994-46cd-8746-9cd66c59241e)

**Comment by n3thshan** [comment]
Can confirm missing icon on KDE plasma ver 6.1.4 with latest version of anki flatpak. However, on gnome, this was not an issue. Please resolve this. Thank you!

**Comment by aug-dev** [comment]
![image](https://github.com/user-attachments/assets/820163cb-6021-47b3-98a8-e3cd7f731f5f)

Hey there!

I can confirm the same issue using KDE Plasma 6.1.4 with Fedora 40.

**Comment by n3thshan** [comment]
Hey! I found a fix. If any of ur apps suffer from this on KDE, right click on the title bar>Configure Special Application Settings>Add Property>Desktop File Name (all the way at the bottom, click on the plus sign)

Then for the value of that property you should type the actual name of the app as defined in the .desktop file. So for anki thats net.ankiweb.Anki. Type this without the .desktop part and apply the settings. Thats it!

**Comment by rayes0** [comment]
it seems this problem only occurs in plasma and is inconsistent across distros, as some are particularly picky about matching the desktop file name.

#181 adds a patch before the build which effectively should do the same thing @n3thshan proposed, involving patching the application name to match net.ankiweb.Anki, which should let plasma match the file without manual intervention.

**Comment by rayes0** [comment]
This should now be fixed, please let me know if you are still having issues.
