### ISSUE TITLE
Anki fails to read adwaita window decorations 

### ISSUE THREAD

**Issue by n3thshan** [flathub/net.ankiweb.Anki#162]
Refer this issue: FedoraQt/QAdwaitaDecorations#73

**Comment by n3thshan** [comment]
further research has made me conclude that pyqt6 bundled with the package does not come with qadwaitadecorations support. I do not think anki themselves will bundle it with their app. However, you, the flatpak maintainer can build the app with it and distribute it as such. please consider this as many use GNOME and will be put off by the inconsistency. This also happens on wayland only and since that is crucial for HiDPI displays (fractional scaling), which are abundant in the market these days, it would be nice to include this. TIA!

**Comment by rayes0** [comment]
There is not a whole lot of benefit currently, so for now building our own version of the app is not planned. However, I am considering doing it in the future to support more platforms than the official builds.

**Comment by n3thshan** [comment]
thanks @rayes0 !!!
