### ISSUE TITLE
Anki asking for login information almost everyday when i click sync 

### ISSUE THREAD

**Issue by barcell1** [flathub/net.ankiweb.Anki#170]
In the beginning this situation didnt happens , but now, everytime the pc rests (idk exatcly the time to trigger this behaviour, but everyday i have to do a login, sometimes more than once a day) and then i try to sync it ask the login information. 
Is there something that i can do ? already tried to reinstall but same issue , maybe some config issue or file missing in my side that are preventing storing the login information.

**Comment by rayes0** [comment]
Might be a configuration issue. Does the issue occur with the non-flatpak version of the app?
