### ISSUE TITLE
Blurry text on gnome using wayland, fractional scaling enabled

### ISSUE THREAD

**Issue by filippo-martini** [flathub/net.ankiweb.Anki#174]
Everything was working fine up to the previous versions, however after an update, the application became extremely blurry (strangely, with the exception of the toolbar).

![image](https://github.com/user-attachments/assets/63c1f3d3-5072-4876-b77a-aac9a292be29)

I tried forcing wayland by disabling x11 and x11 fallback on flatseal, and even passing the ANKI_WAYLAND=1 global variable, but didn't fix the issue.

**Comment by rayes0** [comment]
Try running with these three variables:

```shell
QT_QPA_PLATFORM=wayland
ANKI_WAYLAND=1
QT_SCALE_FACTOR_ROUNDING_POLICY=round
```

`flatpak run --env=QT_QPA_PLATFORM=wayland --env=ANKI_WAYLAND=1 --env=QT_SCALE_FACTOR_ROUNDING_POLICY=round net.ankiweb.Anki`

If it works, try each individually in turn, though it should work with only the last one set: `flatpak run --env=QT_SCALE_FACTOR_ROUNDING_POLICY=round net.ankiweb.Anki`

If the fonts are still messed up, please post your screen resolution and scaling settings.
