### ISSUE TITLE
Wrong scaling

### ISSUE THREAD

**Issue by sommerluk** [flathub/net.ankiweb.Anki#182]
There is now a problem with the scaling. Using KDE Plasma at 125% screen scaling, and Anki scaling at 100%, with the current Flathub Build, I get this:

![screen flathub](https://github.com/user-attachments/assets/a90c680e-fc23-4c9d-bdc2-76510d7e47eb)

The buttons and the list of decks are too small. (You can manually scroll in with the mouse wheel, but this only affects the deck list. The buttons stay too small.)

This was working correctly in previous Flathub packages.

The upstream package does not have this issue. It scales correctly:

![screen upstream](https://github.com/user-attachments/assets/ceb1c738-ffc4-45d6-b787-073bac8b7eb4)

**Comment by sommerluk** [comment]
Also, additional to the scaling size, it seems that in the Flathub package the text "Benutzerdefinierte Sitzung" is much more blurry than in the Upstream package.

**Comment by rayes0** [comment]
This is probably due to 7822faff1c58a434500e9a1f59c45d71ba7a418d, please try running anki as follows and see if scaling matches the non-flatpak version: `flatpak run --env=QT_SCALE_FACTOR_ROUNDING_POLICY=passthrough net.ankiweb.Anki`

**Comment by sommerluk** [comment]
Yes, with `flatpak run --env=QT_SCALE_FACTOR_ROUNDING_POLICY=passthrough net.ankiweb.Anki` scaling matches the non-flatpak version.
