### ISSUE TITLE
Menu has no text

### ISSUE THREAD

**Issue by sommerluk** [flathub/net.ankiweb.Anki#183]
Sometimes, but not always, the menu "Extra" seems to have no visible text:

![screen flathub](https://github.com/user-attachments/assets/5fcde7a9-125a-4b90-bbc2-5da8149ac53d)

This was working correctly on previous Flathub builds and is no issue with the upstream Anki package.

You can nevertheless click on the menu items, and it reacts. But it is of course difficult to find the correct entry when you cannot read them.

As far as I can see, only the Extra menu is affected. I cannot find a way to reproduce this systematically. It happens maybe in 30 % of the cases?

**Comment by sommerluk** [comment]
Would it be feasible to revert to the upstream package instead of building from source? While this might mean sacrificing integration into desktop styles, it would ensure stable functionality.

**Comment by rayes0** [comment]
I believe contents in that tab is provided by add-ons. Please give the full console output when the problem occurs. Does the issue occur running anki without add-ons via `flatpak run net.ankiweb.Anki --safemode`? If not, try updating any add-ons you have installed.

Reverting to using the upstream package is not planned. We are building our own for aarch64 support. If you are still testing with the system information you gave me previously, you are using fairly outdated versions of plasma and a legacy window system. You might have your reasons for not updating and thats fine, but know that upgrading your system might have a decent chance of fixing some of these issues. I have done pretty comprehensive testing of the package across commonly used environments (including x11 on kubuntu) and have not encountered the issues you are describing. 

If you would like to say on the pre-built upstream package for now, install the version from the 7dd65860 (`flatpak update --commit=05baafdf0037c1360e0fa08c18b3ecdb053ff7952751f9e873931d0fb11914c0 net.ankiweb.Anki`) and run `flatpak mask net.ankiweb.Anki` to prevent overriding with later versions. Or just install from the tarball, but in either case you are on your own for updates.

**Comment by sommerluk** [comment]
I found a way to reproduce it.

1. Make sure Anki uses the "Anki" widget style.
2. Close Anki.
3. Start Anki using `flatpak run net.ankiweb.Anki --safemode`. I get this console output:
```
Preparing to run...
Qt warning: Qt: Session management error: Could not open network socket 
2024-12-01 17:11:10,247:INFO:aqt.mediasrv: Serving on http://127.0.0.1:40777
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
Detected locale "C" with character encoding "ANSI_X3.4-1968", which is not UTF-8.
Qt depends on a UTF-8 locale, and has switched to "C.UTF-8" instead.
If this causes problems, reconfigure your locale. See the locale(1) manual
for more information.
Starting main loop...
```
5. Go to Extra -> Settings
6. Choose "Native" as widget style. Console output:
```
Qt warning:   OpenType support missing for "Noto Sans", script 15 
```
7. Close the Settings windows.
8. Click on the Extra menu. It will not display correctly.
9. Close Anki. Console output:
```
2024-12-01 17:11:37,049:WARNING:waitress: unhandled close event
```

Okay. Seems to be a rather particular use case.

Close as WONTFIX?
