### ISSUE TITLE
Anki won't start

### ISSUE THREAD

**Issue by aldevel** [flathub/net.ankiweb.Anki#20]
Flatpak 1.0.7
net.ankiweb.Anki 2.1.8
KDE neon: 5.15
KDE Plasma Version: 5.15.3
KDE Frameworks Version: 5.56.0
Qt Version: 5.12.0
Kernel Version; 4.15.0-46-generic

Suddenly Anki won't start probably after some upgrade. Let me know if I have to try to generate backtrace somehow.

$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=anki --file-forwarding net.ankiweb.Anki
Traceback (most recent call last):
  File "/app/bin/anki", line 6, in <module>
    import aqt
  File "/app/share/anki/aqt/__init__.py", line 14, in <module>
    from aqt.qt import *
  File "/app/share/anki/aqt/qt.py", line 16, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libaom.so.0: cannot open shared object file: No such file or directory

Thanks!

**Comment by nedrichards** [comment]
Apologies. This is being tracked upstream at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/709

For now you can downgrade the runtime:

flatpak update --commit=71faea5b07a69e755b0b3c3694aa5a8903d3a69b09994b0e8ebd8b60d2dc744f org.freedesktop.Platform.html5-codecs

As this is an issue in a different component I'll close this here.
