### ISSUE TITLE
Unable To Copy Text From Anki with Wayland

### ISSUE THREAD

**Issue by cwmke** [flathub/net.ankiweb.Anki#27]
Using Fedora 31 with Gnome Wayland, I am unable to copy text in Anki and paste elsewhere outside of Anki. Also, after copying text in Anki, I can no longer paste from outside Anki into Anki.

**Comment by MisterPresident** [comment]
Having the same issue. Any fix?

**Comment by rayes0** [comment]
I am unable to reproduce this with the latest version of Anki on Fedora 39, Gnome 45 wayland. Please try with the latest version and feel free to let me know if it is still an issue.
