### ISSUE TITLE
Syncing works but causes errors

### ISSUE THREAD

**Issue by Binero** [flathub/net.ankiweb.Anki#3]
Every time I try to Sync with Anki, it generates a popup with the following error: 

```
Syncing failed:
Traceback (most recent call last):
  File "/app/share/anki/aqt/sync.py", line 340, in run
    self._sync()
  File "/app/share/anki/aqt/sync.py", line 407, in _sync
    self._syncMedia()
  File "/app/share/anki/aqt/sync.py", line 441, in _syncMedia
    ret = self.client.sync()
  File "/app/share/anki/anki/sync.py", line 712, in sync
    self.col.media.findChanges()
  File "/app/share/anki/anki/media.py", line 371, in findChanges
    self._logChanges()
  File "/app/share/anki/anki/media.py", line 393, in _logChanges
    (added, removed) = self._changes()
  File "/app/share/anki/anki/media.py", line 415, in _changes
    with os.scandir(self.dir()) as it:
AttributeError: __exit__
```
The syncing seems to work fine otherwise. 

Host system does not show the error. (Arch Linux)

**Comment by njam** [comment]
Possibly a problem with the [flatpak version](https://flathub.org/apps/details/net.ankiweb.Anki).

**Comment by jayesh-bhoot** [comment]
[This post](https://anki.tenderapp.com/discussions/beta-testing/1164-syncing-failed-attributeerror-__exit__-in-210beta37) on Anki Beta forums pinpoints the issue: Python 3.6 is required for the above code to work flawlessly. But the flatpak version refers to Python 3.5.

**Comment by nedrichards** [comment]
This will probably have to wait until the new Freedesktop 1.8 runtime is available then. I'm not sure when exactly the release date for that is - but it's in testing currently.

**Comment by dsd** [comment]
@nedrichards I see there's a new freedesktop 18.08 runtime with python-3.7, but this app actually uses the Kde runtime 5.9 (Anki is incompatible with Qt-5.10). Is the Kde-5.9 runtime going to be updated against the new freedesktop base?

**Comment by nedrichards** [comment]
No. That'll likely happen for the next lts Qt, which I believe is 5.12.

**Comment by nanonyme** [comment]
This is by the way the tracker ticket for KDE runtime port to Freedesktop runtime 18.08 https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/110

**Comment by dsd** [comment]
Sorry that it took a long time to get to this.

I pushed Anki-2.1.4 plus a patch (for now) to make this code py3.5 compatible. There is no longer any error upon sync.
