### ISSUE TITLE
fcitx stopped working on the latest version

### ISSUE THREAD

**Issue by luni3359** [flathub/net.ankiweb.Anki#37]
`fcitx 4.2.9.7-3`
`flatpak Anki 2.1.33`

It used to work before, and now it doesn't acknowledge it exists, even with overrides.

**Comment by m4tx** [comment]
I have the same issue with IBus 1.5.22 and flatpak Anki 2.1.35.

**Comment by JayXT** [comment]
I have the same problem: Anki 2.1.49 simply ignored fcitx5 mozc Japanese input. I wonder what's the root-cause...
