### ISSUE TITLE
Cannot use LaTeX

### ISSUE THREAD

**Issue by laolux** [flathub/net.ankiweb.Anki#39]
This flatpaked version of Anki cannot create cards using LaTeX.

For example create a card with a field containing
`[$]x=0[/$]`

will result in an error message

    Error executing latex.
    Generated file: /var/tmp/anki_temp/tmp.tex
    Have you installed latex and dvipng/dvisvgm?

Importing decks where the LaTeX notes are already processed to images does work.

So, does anyone have an idea of how to enable LaTeX in this flatpak?
Thanks for your help!

**Comment by MarviMcFly** [comment]
@ingemarberg / @dsd I'm using Manjaro as base system with GNOME and having the exact same issue. `latex` is working from the command line as well as other latex programs are working. I also made sure to install `org.freedesktop.Sdk.Extension.texlive` but unfortunately the issue still persists. Did I miss something?

**Comment by ingemarberg** [comment]
@MarviMcFly Have you made sure to install the most recent version of `org.freedesktop.Sdk.Extension.texlive`, i.e., `flatpak install org.freedesktop.Sdk.Extension.texlive//21.08`? If you were to use any older version, for example the 20.08 version that was used for a while, you would get this error.

**Comment by MarviMcFly** [comment]
@ingemarberg Thanks for the quick reply! A bit embarrassing for me, I installed 20.08 while I did not read the output properly and overlooked the 21.08. Once the 21.08 was installed everything worked again! Thank you so much!
```
manjaro@manjaro:~$ flatpak install org.freedesktop.Sdk.Extension.texlive                                                                                                                                      
Looking for matches…
Similar refs found for ‘org.freedesktop.Sdk.Extension.texlive’ in remote ‘flathub’ (system):

   1) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
   2) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/18.08
   3) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/19.08
   4) runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/20.08
```
