### ISSUE TITLE
Foreign fonts partially broken.

### ISSUE THREAD

**Issue by Binero** [flathub/net.ankiweb.Anki#4]
Non-English fonts are broken. They show up fine in the table of the browser view, but they do not show up fine on the overview page or the edit view. I have tested this for Korean and Japanese. Both have fonts installed on the host machine as well.

Host system installation of Anki shows fonts correctly. (Arch Linux)

Example:
![screenshot from 2018-05-01 00-49-43](https://user-images.githubusercontent.com/6867251/39454084-9241c4ac-4cd9-11e8-9226-b943480fdbb4.png)

**Comment by dsd** [comment]
I wonder if this is a strange interaction with the host. Can you check with the latest v2.1.5 and latest Qt5.9 runtime?

I tested with the text "좋아하는 색은 무엇입니까" and can't reproduce (Ubuntu 18.04), shows up fine in all places including the browser edit view.

**Comment by jurf** [comment]
I used to have a similar bug; I believe this is now fixed.

**Comment by Binero** [comment]
I can't reproduce the bug these days, but I am also using a different machine.

I'll close this issue for now, since it appears fixed. If anyone still experiences it they can re-open this issue or create a new one.
