### ISSUE TITLE
Typing in Korean shows up in English

### ISSUE THREAD

**Issue by puelp** [flathub/net.ankiweb.Anki#42]
Flathub Anki does not allow me to type in Korean.

1. select any input area in Anki
2. change the input method to Korean
3. type anything
4. Korean characters should show up, but instead English characters do

Maybe this issue affects CJK characters in general?

**Comment by luni3359** [comment]
I have a similar issue. Are you using fcitx?

Now, does the normal Anki work for you? https://apps.ankiweb.net
There's installation instructions in there, it works perfectly for me and I've started using it in place of the flatpak for the time being.

**Comment by puelp** [comment]
I'm using GNOME and GNOME's input manager, whatever that may be!

I haven't tried normal Anki because I'm a complete noob and I'm 100% sure that I will accidentally delete all my files if I start messing with the command line haha.

**Comment by luni3359** [comment]
It's okay, you won't break your system. I'll guide you through it.
1. Go to the site I linked and click the download button, it should guide you to another button. Click this other blue button too.
![step1](https://user-images.githubusercontent.com/16832398/108631433-93fc4300-742f-11eb-9d1f-ba6dce07f2f4.png)
2. Either the file will be automatically saved to your Downloads folder (located in `~/Downloads`, in other words, `/home/whateveryourusernameis/Downloads`) or you will be prompted to save it. Please put it in `~/Downloads`.
3. Follow the instructions on the website in your terminal. I'll paste them here for your convenience. Like the website says, you don't have to type the `$` symbol. 

My instructions don't have the symbol, so feel free to copy-paste each individual line to your terminal (or type them out manually). If you don't want to type the entire name of the file, you can press Tab once to autocomplete, or twice to show options. If you feel scared or insecure about what you have typed, press `Ctrl + C` and retype what you were just typing.
```
tar xjf Downloads/anki-2.1.40-linux.tar.bz2
cd anki-2.1.40-linux
sudo ./install.sh
```
4. Ta-da! That should be everything. In theory Anki should now be available on your system. Now you can graphically remove the downloaded anki files in your Downloads folder, and Anki will keep working.

If for whatever reason Anki is erroring out when you open it (unlikely), open your terminal again and put this in: `sudo apt install libxcb-xinerama0`, and it should work.

**Comment by puelp** [comment]
Thank you, it worked. :)

**Comment by aggressivepixels** [comment]
This seems to happen with input method frameworks in general. Neither Fcitx nor IBus seem to work with the Flatpak version of Anki, yet they work just fine with the "normal" one. The only other Flatpak in my system is Telegram, and Fcitx seems to work just fine there.

I'm running KDE Neon 5.22.

**Comment by shoop** [comment]
Same for me, Fedora 34 (still need to upgrade) and GNOME. Switching IME to Japanese does not work with this Flatpak.

**Comment by shoop** [comment]
Sorry for the spam but wanted to document my solution.
Turns out that this is due to a missing environment variable: `IBUS_USE_PORTAL=1` -- based on a lucky guess [seen in this link](https://medium.com/hong-kong-linux-user-group/%E4%BF%AE%E6%AD%A3-telegram-desktop-%E5%8F%8A%E5%85%B6%E4%BB%96-qt-%E8%BB%9F%E4%BB%B6%E5%9C%A8-gnome-wayland-%E4%B8%8B%E7%9A%84-ibus-%E4%B8%AD%E6%96%87%E8%BC%B8%E5%85%A5%E5%95%8F%E9%A1%8C-797abc906c3d).

It is possible to [add an override](https://unix.stackexchange.com/a/559130) for yourself by running this:

```
$ flatpak override --user --env=IBUS_USE_PORTAL=1 net.ankiweb.Anki
```

**Comment by JayXT** [comment]
I've got the same problem: flatpak version simply ignores fcitx5 Japanese input. @shoop , do you know whether there is similar variable for fcitx5?

**Comment by JayXT** [comment]
Similar issue for Japanese with fcitx5 mozc input has been created: https://github.com/flathub/net.ankiweb.Anki/issues/56

**Comment by Svadkos** [comment]
`IBUS_USE_PORTAL=1` does fixes ibus for me with or without wayland.
