### ISSUE TITLE
Use freedesktop runtime rather than KDE

### ISSUE THREAD

**Issue by cfergeau** [flathub/net.ankiweb.Anki#51]
The anki flatpak now uses the pre-built upstream anki binaries. These binaries ship with their own builds of the needed shared libs (this includes qt5/pyqt5). There is no need for the copy of these libraries provided by the KDE runtime, so the anki flatpak could use the freedesktop runtime instead.

**Comment by ingemarberg** [comment]
This issue can probably be closed as the Anki Flatpak now uses the Freedesktop runtime.
