### ISSUE TITLE
DISPLAY variable is not set correctly

### ISSUE THREAD

**Issue by juligreen** [flathub/net.ankiweb.Anki#54]
If I execute `print(os.getenv('DISPLAY'))` inside the flatpak Anki debug console, my result is: `:99.0`, even though in a normal shell and inside normal anki it's `:0`

I'm relatively sure that this is breaking an Anki add-on that I'm testing currently, since that's using pynput for global hotkeys.

**Comment by hfiguiere** [comment]
no it's not wrong. It's just sandboxing. Inside the sandbox the X11 display is :99.0. (from an implementation standpoint this determine the path to the unix socket to the X server).

And it's nothing specific to the app.

**Comment by juligreen** [comment]
Thank you, and sorry for this issue then
