### ISSUE TITLE
Typing in Japanese shows up in English

### ISSUE THREAD

**Issue by JayXT** [flathub/net.ankiweb.Anki#56]
Flathub Anki does not allow me to type in Japanese.

- select any input area in Anki
- change the input method to Japanese
- type anything
- Japanese characters should show up, but instead English characters do

Other applications on my Debian 11 install with fcitx5 mozc work as expected and support Japanese input.

**Comment by JayXT** [comment]
It seems like the underlying problem might be in outdated org.kde.Platform runtime according to this [thread](https://github.com/flatpak/flatpak/issues/2031#issuecomment-1007436193).
Could you please update it to the newer version? Supposedly version 5.15-21.08 should work, but I'm not sure how to verify this.

**Comment by luni3359** [comment]
It seems like there's no maintainers at the moment. There might be an easy solution like the ibus one, but in the meantime I'd recommend downloading the program itself from the official website. Especially if you really need to study your flashcards right away.

**Comment by laolux** [comment]
I use the anki flatpak with ibus-anthy and the japanese input works just fine. At least when using Anki on wayland as native wayland app, haven't tried x11 mode. So might be a workaround until fcitx5 is working.

**Comment by JayXT** [comment]
@laolux, as it turned out, currently the workaround is to add fcitx5 input library manually as is mentioned here:
https://forums.ankiweb.net/t/add-fcitx5-support/16477
Although, I haven't checked it with a flatpak installation and switched to the official binary instead.

**Comment by laolux** [comment]
@JayXT glad it's working for you. I am not sure how easy it would be to add the library to the flatpak, I had some issues adding a simple TeX package to a flatpak app.

**Comment by JayXT** [comment]
@laolux , I think the library should be added in the upstream. That's the reason I've created the request on the Anki forums.
