### ISSUE TITLE
Does not start on Wayland any more after commit 112f90039b

### ISSUE THREAD

**Issue by rmader** [flathub/net.ankiweb.Anki#65]
Commit 112f90039b forces the Wayland backend in Wayland sessions however Anki still reports the following:
> Wayland support is disabled by default due to bugs:
> https://github.com/ankitects/anki/issues/1767
> You can force it on with an env var: ANKI_WAYLAND=1
> Qt info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. 
> Qt warning: could not connect to display  
> Qt info: Could not load the Qt platform plugin "xcb" in "" even though it was found. 
> Qt fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

I guess the commit should be reverted in the meantime.

---

workaround: `flatpak override --user --env=ANKI_WAYLAND=1 --env=QT_QPA_PLATFORM=wayland net.ankiweb.Anki`

**Comment by rmader** [comment]
cc @ingemarberg

**Comment by ingemarberg** [comment]
I'm very sorry about this mistake. I've pushed a change reverting this in #66 and also verified that it works in both X11 and Wayland. Please let me know that it's working for you as well. Once again, sorry about this. I'm still learning and this was rather embarrassing.

**Comment by rmader** [comment]
> Once again, sorry about this. I'm still learning and this was rather embarrassing.

No worries, thanks for the fast reaction and for taking care of the package!

**Comment by rmader** [comment]
P.S.: IMO it's a bug in Anki that it doesn't allow the Wayland backend when X11 is not available. Firefox for example, which also still defaults to X11, does that.

**Comment by violoncelloCH** [comment]
Thanks for this fix and the workaround (which is working) !
I'm not familiar to the flatpak/flathub build system, but just wondering, is there already a new release under way? Or for when is it planned? Thank you very much :)

**Comment by ingemarberg** [comment]
@violoncelloCH The new version was released sometime last night (CEST). I've tried installing it and it seems to work fine under Wayland by using the X11 backend.

**Comment by violoncelloCH** [comment]
thank you very much ! yes I can also confirm it to be working on Fedora 35 and 36 (wayland)
