### ISSUE TITLE
Can someone check on the bug tracker PL

### ISSUE THREAD

**Issue by NameLessGO** [flathub/net.ankiweb.Anki#77]
Tried making a commit, but the bot build resulted in error [PL bug tracker](https://github.com/flathub/net.ankiweb.Anki/pull/76)

**Comment by ingemarberg** [comment]
I'm sorry for not responding earlier. If I recall correctly, there were some errors with the x-checker-data metadata around this time. This is probably why your pull request wasn't built successfully. I'll gladly accept your pull request, but it needs to be updated first to be able to be merged. Please use _Update with rebase_.
