### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

### ISSUE THREAD

**Issue by NoobieOnGitHub** [flathub/net.ankiweb.Anki#83]
Anki does not open, instead gives this error 
Anki starting...
Traceback (most recent call last):
  File "aqt", line 13, in <module>
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-2: ordinal not in range(256)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "aqt", line 15, in <module>
Exception: Anki requires a UTF-8 locale.

https://i.imgur.com/hfRhwZI.png

**Comment by mwleeds** [comment]
Can you post the output of the command `localectl`? For me it's this:
```
$ localectl
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us-dvorak
      X11 Layout: us
     X11 Variant: dvorak
```

You can see from the `.UTF-8` suffix on the language that there's Unicode support (UTF-8 is a common encoding for Unicode, which is a standard used for encoding characters from many languages as well as things like emojis). I infer that your language won't have such a suffix and perhaps that's related to the language you chose when you set up your computer?

**Comment by NoobieOnGitHub** [comment]
![image](https://user-images.githubusercontent.com/99780388/210150250-c5fb867f-016f-4201-8b42-2f1c516e9ea3.png)

**Comment by NoobieOnGitHub** [comment]
Well, I changed my system to Linux Mint and now the bug does not exist.
