### ISSUE TITLE
Refuses to start: AttributeError: 'ThemeManager' object has no attribute 'default_palette'

### ISSUE THREAD

**Issue by Fregf** [flathub/net.ankiweb.Anki#91]
After an update, Anki only gives this error message at start:

⁨```
Traceback (most recent call last):
  File "aqt.main", line 201, in __init__
  File "aqt.main", line 250, in finish_ui_setup
  File "aqt.toolbar", line 274, in draw
  File "aqt.webview", line 495, in stdHtml
  File "/home/john/.var/app/net.ankiweb.Anki/data/Anki2/addons21/1431333984/Change_Font.py", line 325, in standard_css_new
    palette = theme_manager.default_palette
AttributeError: 'ThemeManager' object has no attribute 'default_palette'
```

```
# flatpak info net.ankiweb.Anki

Anki - Powerful, intelligent flash cards

          ID: net.ankiweb.Anki
         Ref: app/net.ankiweb.Anki/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.1.57
     License: AGPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 462.8 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 23ac4cd3371c7d3bb6b4a5d5bb9b8d90ced7706ae92d2415b0c85edda50c025c
      Parent: 559a3305963e0b4003f09a6113e5b401ad78c0d303a098252941cbb7511163c6
     Subject: Fix formatting error in release notes (f40898b9)
        Date: 2023-02-11 08:48:20 +0000
```

The system is running Debian testing with Cinnamon desktop.

**Comment by Fregf** [comment]
downgrading to the flatpak from commit 559a3305963e0b4003f09a6113e5b401ad78c0d303a098252941cbb7511163c6 fixes the problem.

**Comment by ingemarberg** [comment]
I don't think this is related to the Flatpak itself. Instead, the error message seems to be generated by an addon, which uses the style default_palette. However, support for default_palette was removed in Anki 2.1.57 (cf. https://github.com/ankitects/anki/commit/f169ee093384ab3509dc0a954aa3f153df574d29). Could you try filing a bug for the addon?

**Comment by rayes0** [comment]
Closing for now as this is an add-on specific problem.
